### ISSUE TITLE
Empty mini drawer

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/CrossfadeDrawerLayout#1]
I implemented It, but when I open The mini drawer, i get an empty one. Only account header image.

**Comment by EpsilonOrionis** [comment]
Solved. It seems to work only with PrimaryDrawerItem

**Comment by mikepenz** [comment]
@EpsilonOrionis you have to allow `SecondaryDrawerItems` to be shown in the `MiniDrawer` ;)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L75

**Comment by EpsilonOrionis** [comment]
Sorry man, my bad :D

**Comment by mikepenz** [comment]
@EpsilonOrionis no problem ;)
