### ISSUE TITLE
MiniDrawer closing gesture

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/CrossfadeDrawerLayout#10]
Hi Mike, is it normal that MiniDrawer closing gesture can ne performed only with a tap? I mean when I open it swiping right I try to close it swiping left, but it isn't working. I close it by tapping the screen. Is this a correct behavior or not?

P.S. Sorry for my English

**Comment by mikepenz** [comment]
@EpsilonOrionis do you talk of the normal `MiniDrawer` or about the `CrossfadeDrawerLayout` with the `MiniDrawer` 

**EDIT** Sorry missed that we are in the project of the `CrossfadeDrawerLayout` :D Will check it later today

**Comment by EpsilonOrionis** [comment]
No problem, let me know :D

**Comment by mikepenz** [comment]
fixed in v0.2.0 ;)

**Comment by EpsilonOrionis** [comment]
Thank you Mike, you're always available :)

**Comment by mikepenz** [comment]
i hope it works now as expected :)

**Comment by EpsilonOrionis** [comment]
It's working as expected :) Oh another question, how can I detect onOpen?

**Comment by mikepenz** [comment]
hmmm as it's a `DrawerLayout` with the normal listeners it provides

**Comment by EpsilonOrionis** [comment]
Can you make me an example?

**Comment by mikepenz** [comment]
@EpsilonOrionis you need to know when the drawer is opened right? not for the event when the miniDrawer was changed to the normal drawer?

**Comment by EpsilonOrionis** [comment]
In Lollipop+ devices we can make the status bar transparent right? I love it. I want to make the status bar transparent during the miniDrawer open animation.

**Comment by mikepenz** [comment]
The default `CrossfadeDrawerLayout` sample of the `MaterialDrawer` has the `MiniDrawer` below the `Statusbar` yes. 

Regarding your previous question. which `open` do you want to detect? and why?

**Comment by EpsilonOrionis** [comment]
First question: Changing
Second question: Because it's nice. The MaterialDrawer will be under the transparent status bar.

**Comment by mikepenz** [comment]
@EpsilonOrionis you mean chaning from `MiniDrawer` to the normal `Drawer` right?

**Comment by EpsilonOrionis** [comment]
Yep

**Comment by mikepenz** [comment]
you can provide a `CrossfadeListener` and check when it is completely slided into one direction:
https://github.com/mikepenz/CrossfadeDrawerLayout/blob/develop/library/src/main/java/com/mikepenz/crossfadedrawerlayout/view/CrossfadeDrawerLayout.java#L87

**Comment by EpsilonOrionis** [comment]
How can I use it? Sorry if I'm pedant, but your library is the only one that fits my needs. And it's awesome!

**Comment by mikepenz** [comment]
@EpsilonOrionis as far as i know it is also the only library providing such kind of behavior :D

something like this:

``` java

        //hook to the crossfade event
        crossfadeDrawerLayout.withCrossfadeListener(new CrossfadeDrawerLayout.CrossfadeListener() {
            @Override
            public void onCrossfade(View containerView, float currentSlidePercentage, int slideOffset) {
                if (currentSlidePercentage == 0) {
                    Log.e("CrossfadeDrawerLayout", "MiniDrawer shown (closed)");
                } else if (currentSlidePercentage == 100) {
                    Log.e("CrossfadeDrawerLayout", "Normal Drawer shown (opened)");
                }
            }
        });
```

**Comment by EpsilonOrionis** [comment]
Yes you're right,  and everybody knows it :D. Ok aaaand will it work even if currentSlidePercentage is between 0 a 100? Maybe I can use e.g: else if (currentSlidePercentage > 100). What do you think about it?

**Comment by mikepenz** [comment]
@EpsilonOrionis  haha if you check > 100 you will never have a match :D as it is exact 100 :P You should probably check for the exact values as this is called many times if the slide is done. so for each new slide percentage value. 
not sure what you will do if it is opened but you can try it :P

**Comment by EpsilonOrionis** [comment]
What a mess! And you're laughing! I'm ruined hahahahahahahahahah :D

**Comment by mikepenz** [comment]
@EpsilonOrionis haha there are things worse than that :smile: to be fair. it was luck i saw it. It's 02:00am at my place and i have to get up in less than 5hours. 

so i hope my hints helped you :P. I'm out for today.

**Comment by EpsilonOrionis** [comment]
Where are you from? I'm Italian.

**Comment by mikepenz** [comment]
Austria :P (the one in europe :P. just in case you missread it as Australia :P)

**Comment by EpsilonOrionis** [comment]
I'm in Europe too, I know the Austria you're talking about :D

**Comment by mikepenz** [comment]
Haha :D Where are you from?

**Comment by EpsilonOrionis** [comment]
Italy, Puglia is the region's name

**Comment by mikepenz** [comment]
Ah :D So the same time zone :P. I am off now. Good night.

**Comment by EpsilonOrionis** [comment]
Night
