### ISSUE TITLE
Cross fade / mini drawer issue

### ISSUE THREAD

**Issue by Alex293** [mikepenz/CrossfadeDrawerLayout#12]
Hi,

The mini drawer have an issue with the cross fader, i don't know if it come from the drawer or the cross fader.

When for the first time you build those, the click listener will be active for the items on the drawer (pane) even if its closed. The bug only appear the first tim i.e. if you open then close the pane everything works at it should. You can reproduce the bug on your demo its not coming from me bad using your lib.

I tried to open then close the pane by code it but it only work by swipe.

I've a quick fix consisting of adding and deleting listener for mini and normal drawer when pane is closed/opended but i'am still able to see click animations so the bug is still there.

**Comment by mikepenz** [comment]
@Alex293 once again wrong repo :D This one would be the correct one: https://github.com/mikepenz/Crossfader
I added a fix for API >= 11 on the `Crossfader`
