### ISSUE TITLE
Show mini drawer on start

### ISSUE THREAD

**Issue by bingjiang** [mikepenz/CrossfadeDrawerLayout#13]
I want to open the mini drawer on start app, therefore I called **result.openDrawer()**. It works.

However, when I want to expand out the drawer to full view by swiping right, the drawer is stuck and won't expand.

May I know how to achieve this behaviour?

I tried to meddle with ICrossfader in order to try to solve above. I put some breakpoints in this sample code, it seems like the listener methods of ICrossfader is never called. I am not sure of how the ICrossfader() works but if I comment it out, there seems to be no difference in behaviour.

``` java
//define the crossfader to be used with the miniDrawer. This is required to be able to automatically toggle open / close
        miniResult.withCrossFader(new ICrossfader() {
            @Override
            public void crossfade() {
                boolean isFaded = isCrossfaded();
                crossfadeDrawerLayout.crossfade(400);

                //only close the drawer if we were already faded and want to close it now
                if (isFaded) {
                    result.getDrawerLayout().closeDrawer(GravityCompat.START);
                }
            }

            @Override
            public boolean isCrossfaded() {
                return crossfadeDrawerLayout.isCrossfaded();
            }
        });
```

**Comment by mikepenz** [comment]
fixed in v0.3.3
