### ISSUE TITLE
Right drawer

### ISSUE THREAD

**Issue by kibotu** [mikepenz/CrossfadeDrawerLayout#14]
How do I add a right drawer? 

I've tried with

`new DrawerBuilder()
                .withActivity(this)
                .withDrawerGravity(Gravity.END)
                .append(result);`

but it has an unwanted behaviour with the crossfade on the left side then. Any suggestions of what I did wrong?

**Comment by mikepenz** [comment]
@kibotu you only can have one slider with the `CrossfadeDrawerLayout` you may want to do a Pull Request to enable the same behavior for both sides.

**Comment by kibotu** [comment]
aww ok thanks for the feedback :)

**Comment by mikepenz** [comment]
No problem. I'm sorry that this is not as easy. It is a very rare case that you want to have 2 `MiniDrawer`
