### ISSUE TITLE
OnDrawerItemClickListener not always called (CrossfadeDrawerLayout)

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/CrossfadeDrawerLayout#15]
_From @codeAbode on June 18, 2016 21:13_

Sometimes when I press on a drawer item, the listener is not called and the item needs to be pressed again. Below is my drawer click listener:

``` java
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.d(TAG, "onItemClick: "+position);
                            switch(position){
                                case 1:
                                    if(context.getClass() !=  MainActivity.class){
                                        Intent s = new Intent(context, MainActivity.class);
                                        context.startActivity(s);
                                    }
                                    break;
```

And this is a snippet of my drawer builder:

``` java
 final Drawer drawer = new DrawerBuilder()
                .withActivity((Activity) context)
                .withHasStableIds(true)
                .withToolbar(toolbar)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withSliderBackgroundColor(ContextCompat.getColor(context, R.color.darkgrey))
                .withDrawerWidthDp(72)
                .withDelayDrawerClickEvent(-1)
                .withAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
                .withCloseOnClick(true)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.home_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_home).withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
```

_Copied from original issue: mikepenz/MaterialDrawer#1345_

**Comment by mikepenz** [comment]
@codeAbode are you sure you click correctly and don't move the finger out of the view or moved the view? Never experienced anything similar. 

On which device with which android version did you get this issue?

Anyhow reproduceible?

**Comment by mikepenz** [comment]
_From @codeAbode on June 18, 2016 22:14_

Thanks for the quick response. I am using this on api 23 and its quite a regularly occurence. Seems to work fine on my emulator but on my galaxy s7 it doesn't work. Note this is only the case when the draw is fully expanded. When it is a mini drawer all the clicks work all the time

**Comment by mikepenz** [comment]
_From @codeAbode on June 18, 2016 22:15_

This also happens when the drawer icon is clicked. Sometimes it doesn't register and it must be clicked twice.

**Comment by mikepenz** [comment]
_From @codeAbode on June 18, 2016 22:53_

Sorry for all the comments. 

As for reproducing it use your demo Material Drawer app. It has the same issues with the CrossFadeDrawerLayout.

**Comment by mikepenz** [comment]
@codeAbode thank you for the comments you made, and for the effort you put into providing all the comments. 

But I am afraid I have to give you an answer you do not really want to hear. 

I assume that your issue is a device (or OS (samsung)) related one, as you have the same issue for the drawer icon. Which is not handled by the `MaterialDrawer`. 

It's the `ActionBarDrawerToggle` directly from the appcompat libs. 

For the items in the drawer itself, they have a normal `OnClickListener` set on the `itemView` nothing which can be changed there. So if the `listener` is not called, it's an OS issue. So maybe a issue from Samsung, or yeah. perhaps also the device screen or the touch is broken?

**Comment by mikepenz** [comment]
_From @codeAbode on June 19, 2016 15:51_

@mikepenz 

This may be an issue I should have posted in the CrossfadeDrawerLayout. I have not looked a lot into your code but I think its an issue with the drawer closing. 

If the crossfade drawer is expanded it registers a touch event as if you were sliding the drawer so the OnItemClick is never triggered. You have to play with it a bit but basically whatever is capturing the drawer to slide back to a compact state is taking control over an OnItemClick event.

**Comment by mikepenz** [comment]
@codeAbode seems like your assumption with the `CrossfadeDrawerLayout` is right. Weird enough is that I have not modified the original `closeDrawers` function and just call this one, after the item was clicked. Which should theoretically do the same as the drawer does internally. 

One thing could be really true, that you may slide a bit so it is not detected as click. But it is really hard to reproduce this one. 

Its a lot easier to reproduce the `ActionBarDrawerToggle` not fireing issue, just select an item in the normal drawer, and it won't work. but it works if the mini drawer is clicked.

**Comment by mikepenz** [comment]
To be honest I have no idea why it reacts like this. I tried to close the drawer inside a `handler` tried to sync the state of the `ActionBarDrawerToggle` tried to set the full drawers view to INVISIBLE instead of GONE. Tried to close the drawer via different APIs and so on. Nothing really changes the behavior.

**Comment by mikepenz** [comment]
_From @codeAbode on June 19, 2016 19:34_

I'll dive into your code and trying playing with it over the next week

**Comment by mikepenz** [comment]
@codeAbode yes. :/ I can't describe what possibly could go wrong here.

**Comment by mikepenz** [comment]
@codeAbode we may should move this to the `CrossfadeDrawerLayout`

**Comment by mikepenz** [comment]
@codeAbode you have found out something?

**Comment by mikepenz** [comment]
@codeAbode after some more debugging. It seems to be a bug in the `DrawerLayout` itself. If I disable all animations when closing the `drawer` (overwriting all `closeDrawer` methods and set animation to `false`)  it works without problems. 

It is also interesting to note that it will work with animation if I set a `breakpoint` into the `onViewDragStateChanged` method Line 2088 inside the `DrawerLayout`, that it will work without problems. 

Seems like some kind of race condition happens there.

**Comment by mikepenz** [comment]
Oh after some more debugging I found out why it was working without animation, and with debugging in this method. It was related to the `lp.onScreen` being < 0 (which is the param used to identify if `onDrawerClosed` has to be called which will refresh the state of the `ActionBarDrawerToggle`) So it came to my mind that maybe the animation for crossfading is playing during the animation for closing the `DrawerLayout` which results in a `lp.onScreen < 0` and I was right. So the simple fix was to just clear the animation of the `mContainer` in all `closeDrawer` methods  for the `CrossfadeDrawerLayout`.  

The fix is in the newest version

**Comment by wilsonhws** [comment]
Hi, i have tried your latest version, but the problem still remains, my phone is samsung S7 edge running on android 7.0, sony xperia Z3 on android 6.0.1, HTC oneX android 4.2.2

But it works on oneplus 3 on android 8.0 and honor 6 android 4.4.
