### ISSUE TITLE
CrossfadeDrawerLayout below status bar and App bar

### ISSUE THREAD

**Issue by kennyung6** [mikepenz/CrossfadeDrawerLayout#16]
@mikepenz. Thanks for this great library, its indeed helpful.. my issue is that i can't figure out how to make the cross fade drawer layout show behind the ActionBar/APP Bar. I tried using

.withDrawerLayout(R.layout.crossfade_drawer).withRootView(R.id.miniDrawer).withRootView(R.id.drawer_container) But i was getting: "Relative layout" cannot be cast into drawerlayout.

I went through previous issues to see if i could find similar question but couldn't find one. i also tried using the **.withBelowStatusBar** still problem persist.

Below is my cross fade drawerlayout.xml

```
<android.support.v7.widget.Toolbar
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:background="?attr/colorPrimary"
    android:elevation="4dp"
    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />
<!-- the layout which will contain (host) the drawerLayout -->
  <FrameLayout
      android:id="@+id/drawer_container"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:layout_below="@id/toolbar">

<com.mikepenz.crossfadedrawerlayout.view.CrossfadeDrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/material_drawer_layout"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fitsSystemWindows="true" />

  </FrameLayout>
```

Thanks in anticipation.
Regards

**Comment by mikepenz** [comment]
@kennyung6 please have a look on the `CustomContainerActivity` of the sample app. It shows exact the same use-case just with a normal `DrawerLayout`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by kennyung6** [comment]
Thanks @mikepenz
