### ISSUE TITLE
Navigation drawer full screen

### ISSUE THREAD

**Issue by Rushabhs999** [mikepenz/CrossfadeDrawerLayout#17]
How to prevent fullscreen navigation drawer ?

**Comment by mikepenz** [comment]
@Rushabhs999 what do you mean?

**Comment by Rushabhs999** [comment]
Navigation drawer starts from status bar i want to start it from action bar

**Comment by mikepenz** [comment]
@Rushabhs999 that's nothing library related. Please look up google on how to use a `DrawerLayout` in your xml file. 

--> If you use the MaterialDrawer (then you opened the issue in the wrong place) then please head over to the proper project page, and look in the sample app. it shows this case
