### ISSUE TITLE
Graphical issue

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/CrossfadeDrawerLayout#3]
Sometimes when I open and close the MiniDrawer, a trace of the MaterialDrawer icons remain slightly visible in the MiniDrawer.

**Comment by mikepenz** [comment]
@EpsilonOrionis could you please add a screenshot?

**Comment by EpsilonOrionis** [comment]
Ok, I'll add a screenshot when it become visible again

**Comment by mikepenz** [comment]
@EpsilonOrionis will close that for now.
