### ISSUE TITLE
Trying to get library from gradle

### ISSUE THREAD

**Issue by moyvera** [mikepenz/CrossfadeDrawerLayout#5]
Just adding your dependency I can't download it, I'm get next issue...

Error:(44, 13) Failed to resolve: com.mikepenz:crossfadedrawerlayout:0.0.1-SNAPSHOT
<a href="openFile:/Users/*.*/AndroidstudioProjects/appname/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Do you any idea about it ?

**Comment by mikepenz** [comment]
The library is only on the SNAPSHOT repository of maven at the moment. 

In the README there's  the information how you can add this repo
https://github.com/mikepenz/CrossfadeDrawerLayout#using-maven
