### ISSUE TITLE
Update MiniDrawer

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/CrossfadeDrawerLayout#6]
I'm trying to update the AccountHeader image, and I do it, but only for the MaterialDrawer.
I update the MiniDrawer with this:

miniResult.getAccountHeader().updateProfile(BITMAP_IMAGE_HERE); but it remains as it was.

**Comment by mikepenz** [comment]
@EpsilonOrionis you can recreate the items inside the `MiniDrawer` by calling the following method: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L363

Oh and this is no `CrossfadeDrawerLayout` question :D You should have opened this inside the `MaterialDrawer` repo ;)

**Comment by EpsilonOrionis** [comment]
Thanks :D
