### ISSUE TITLE
How to change the icon background on selection.

### ISSUE THREAD

**Issue by ashokslsk** [mikepenz/CrossfadeDrawerLayout#7]
Hi mike, 
How can i change the mini drawer list item selection color.  By default it has similar to blue color but i want to change which suits my drawer color.

**Comment by mikepenz** [comment]
@ashokslsk the `MiniDrawer` is a feature from the `MaterialDrawer` not from this project. Please open an issue on the correct github project ;)

**Comment by mikepenz** [comment]
If you define that the `MiniDrawer` should have a background it will choose the same background as for normal `DrawerItems` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/MiniDrawerItem.java#L112

**Comment by ashokslsk** [comment]
Hi Mike, 

I mean in the crossfadedrawerlayout only. 
say i have my custom icon in the crossfadedrawerlayout list item and how can give the selected effect like that this list item is clicked let me add test screen.
![test](https://cloud.githubusercontent.com/assets/1325300/11494667/d669bcfe-982a-11e5-9197-6fc74eab2af5.png)

**Comment by mikepenz** [comment]
@ashokslsk as mentioned this is the `MiniDrawer` the `CrossfadeDrawerLayout` is only responsible for resizing the views and handling the drag

**Comment by mikepenz** [comment]
Probably you are searching for this: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L124

as mentioned this is `MiniDrawer` (so `MaterialDrawer` specific)
