### ISSUE TITLE
custom icon selection color or effect.

### ISSUE THREAD

**Issue by ashokslsk** [mikepenz/CrossfadeDrawerLayout#8]
Hi @mikepenz , 

In CrossfadeDrawerLayout how can i have the drawer item custom icon selected effect.
say i have my custom icon in the crossfadedrawerlayout list item and how can give the selected effect like that this list item is clicked let me add test screen. 
![test](https://cloud.githubusercontent.com/assets/1325300/11494667/d669bcfe-982a-11e5-9197-6fc74eab2af5.png)

**Comment by mikepenz** [comment]
as noted in #7
